name: lcats

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: log-cache-acceptance-tests
  version: latest

instance_groups:
- name: lcats
  azs:
  - z1
  instances: 1
  vm_type: minimal
  stemcell: default
  lifecycle: errand
  networks:
  - name: default
  jobs:
  - name: lcats
    release: log-cache-acceptance-tests
    consumes:
      log-cache: {from: log-cache, deployment: cf}
    properties:
      log_cache_cf_auth_proxy: ((log_cache_cf_auth_proxy))
      uaa_url: ((uaa_url))
      client_id: lcats
      client_secret: ((lcats_client_secret))
      skip_cert_verify: ((skip_cert_verify))

update:
  canaries: 10
  max_in_flight: 10
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000
  serial: true
